### ISSUE TITLE
Populate hook with array of one ref return object not an array.

### ISSUE THREAD

**Issue by ducnvhn** [feathersjs-ecosystem/feathers-hooks#174]
### Steps to reproduce
Here is my post schema in mongodb : 
````
...
comments: [ {type: Schema.Types.ObjectId, ref: 'Comment'}]  //array of ref to comment
...
````
and the populate schema in the feather hook 
````
const populateCommentSchema = {
 include: [
   service: 'comments',
   nameAs: 'comments',
   parentField: 'comments',   //the field in the Post schema
   childField: '_id'    //the field in the Comment schema
 ]
};
````
The post hook object:
````
const postHooks = {
  .....
  after: {
    ...
    find: [populate({ schema: populateCommentSchema  })]
    ...
  }
}
````
### Expected behavior
when I try to populate ````Comments ```` when calling ````find```` service method , the result should contain an array of Comments.

### Actual behavior
But if the ````Post```` have just one ref of ````Comment```` in the array, the result of ````comments```` is just one object. 

Did I made the wrong populate schema ? or something I missed along the way ? Please point me out. 
Thank you very much.

**Comment by daffl** [comment]
Please reopen in https://github.com/feathers-plus/feathers-hooks-common/issues/new
